apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: block.csi.vultr.com
spec:
  attachRequired: true
  podInfoOnMount: true

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vultr-block-storage
  namespace: kube-system
provisioner: block.csi.vultr.com
allowVolumeExpansion: true
parameters:
  block_type: high_perf

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vultr-block-storage-retain
  namespace: kube-system
provisioner: block.csi.vultr.com
allowVolumeExpansion: true
reclaimPolicy: Retain
parameters:
  block_type: high_perf

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vultr-block-storage-hdd
  namespace: kube-system
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: true
provisioner: block.csi.vultr.com
parameters:
  block_type: storage_opt

---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: vultr-block-storage-hdd-retain
  namespace: kube-system
allowVolumeExpansion: true
provisioner: block.csi.vultr.com
reclaimPolicy: Retain
parameters:
  block_type: storage_opt